### ISSUE TITLE
[GI-Prof-Gest-14] Créer un cours

### ISSUE THREAD

**Issue by SK0RPIA** [SK0RPIA/e-music-data#14]
En tant que gestionnaire
- Je peux créer des cours
- Afin de planifier les cours de l’année

- [x]  Refaire le diagramme de classes 
- [x]  Faire Entité / Relations 
- [x]  Peupler la base de donnée
- [x] Créer le controller cour 
- [x] Créer la vue twig 
- [x] Créer le formulaire d'ajout d'un cour 

### Critères d'acceptation métier: 

- [x] Que le nouveau cours se génère bien dans la base de donnée

**Comment by Alexia50** [comment]
0) Refaire le diagramme de classes 
1) Faire Entité / Relations 
2) Peupler la base de donnée
3) Créer le controller cour 
4) Créer la vue twig 
5) Créer le formulaire d'ajout d'un cour

**Comment by Alexia50** [comment]
[e-music.pdf](https://github.com/SK0RPIA/e-music-data/files/10030661/e-music.pdf)

**Comment by jcheron** [comment]
> 0. Refaire le diagramme de classes
> 1. Faire Entité / Relations
> 2. Peupler la base de donnée
> 3. Créer le controller cour
> 4. Créer la vue twig
> 5. Créer le formulaire d'ajout d'un cour

Ces tâches seraient mieux placées dans le descriptif de l'issue :
Ca permet de les cocher, en tant que task, et de visualiser un avancement

Penser à ajouter également dans l'issue les critères d'acceptation (métier pour le client)
