### ISSUE TITLE
[GI-Gest-27] Gérer les cours (Création, modification, suppression)

### ISSUE THREAD

**Issue by SK0RPIA** [SK0RPIA/e-music-data#27]
En tant que Gestionnaire
- Je peux gérer les cours
- Afin de mettre à jour les informations relatives à ces cours.

**Comment by Alexia50** [comment]
rajout de modifier un cour 
pas besoin pour supprimer 
![image](https://user-images.githubusercontent.com/89576534/213701191-0c4a5bbc-a66d-4ee2-a23b-cf0746a57bcf.png)

**Comment by Alexia50** [comment]
modifier un cour : 
![image](https://user-images.githubusercontent.com/89576534/213701297-59e037cc-1bcf-4d17-b4d8-978c9ce65f04.png)
